include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**.g.dart"
    - "**.gr.dart"
    - "**.freezed.dart"

  errors:
    todo: ignore
    invalid_annotation_target: ignore
    avoid_catches_without_on_clauses: ignore
    document_ignores: ignore
    avoid_print: ignore

linter:
  rules:
    public_member_api_docs: false
