name: flexi_localization
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  analyzer: 7.3.0
  build: 2.4.2
  build_runner: 2.4.15
  equatable: 2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: 2.5.2
  source_gen: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: 3.0.4
  json_serializable: 6.9.4
  very_good_analysis: 7.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/lang/en.json
    - assets/lang/tr.json
